# Generated by Django 3.2.3 on 2021-05-24 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_index=True)),
                ('data_emissao', models.DateTimeField(auto_now=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
        ),
    ]
