# Generated by Django 3.2.3 on 2021-05-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '__first__'),
        ('clientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_index=True)),
                ('data_emissao', models.DateTimeField(auto_now=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('rentabilidade_pedido', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_de_descontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_multiplo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('produto_nome', models.CharField(max_length=100)),
                ('produto_preco_tabela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rentabilidade_produto', models.IntegerField(blank=True, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produto')),
            ],
        ),
    ]
