# Generated by Django 3.2.3 on 2021-06-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='rentabilidade_produto',
        ),
    ]
