# Generated by Django 3.2.3 on 2021-06-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_pedido', '0002_remove_itempedido_rentabilidade_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='rentabilidade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
