# Generated by Django 3.2.2 on 2021-05-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('excluido', models.BooleanField(default=False)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
